# Generated by Django 5.0.3 on 2024-03-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_field', models.ImageField(upload_to='museum_gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('img_field', models.ImageField(blank=True, null=True, upload_to='museum_gallery/')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.museumcategory')),
            ],
        ),
    ]
