# Generated by Django 5.0.3 on 2024-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumtopic',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
