# Generated by Django 5.0.3 on 2024-03-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_museumtopic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumcategory',
            options={'verbose_name_plural': 'Museum Categories'},
        ),
        migrations.AlterModelOptions(
            name='museumtopic',
            options={'verbose_name_plural': 'Museum Topics'},
        ),
    ]
