# Generated by Django 5.0.3 on 2024-03-17 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_museumcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='museumtopic',
            name='author',
            field=models.CharField(default='admin', max_length=150),
        ),
        migrations.AddField(
            model_name='museumtopic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museumtopic',
            name='created_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='topic_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museumtopic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
