# Generated by Django 5.0.3 on 2024-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_museumtopic_author_museumtopic_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museumtopic',
            name='author',
        ),
        migrations.AddField(
            model_name='museumtopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
