# Generated by Django 5.0.3 on 2024-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_remove_museumtopic_author_museumtopic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
