
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: "prometheus-alfa-web"
    metrics_path: /metrics

    static_configs:
      - targets: ["alfaromeo.azurewebsites.net"] # ["localhost:8000"]
