apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  namespace: alfa-romeo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
