apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: alfa-romeo
type: Opaque
stringData:
  DATABASE_USER: "your_db_user"
  DATABASE_PASSWORD: "your_db_password"
  SECRET_KEY: "your-django-secret-key-min-50-chars"
  POSTGRES_USER: "your_db_user"
  POSTGRES_PASSWORD: "your_db_password"
  POSTGRES_DB: "alfa_romeo_db"
