# Generated by Django 5.0.3 on 2024-04-08 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('shipping_address_two', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('town', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('zip', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
