# Generated by Django 5.0.3 on 2024-04-25 15:59

import alfa_romeo_web.checkout.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), alfa_romeo_web.checkout.validators.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='town',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), alfa_romeo_web.checkout.validators.validate_no_digits]),
        ),
    ]
