# Generated by Django 5.0.3 on 2024-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shoppingcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
