# Generated by Django 5.0.3 on 2024-03-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
