# Generated by Django 5.0.3 on 2024-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_comment_replies_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
