apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
    # This is a Kubernetes volume type that mounts a directory from the host node's filesystem 
    # into the container. In this case, the path /mnt/data/postgres on the Kubernetes node
    # (the machine where the pod is scheduled) will be mounted into the container.
  storageClassName: manual # check storage classes (kubectl get storageclasses)
