apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfa-romeo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfa-romeo-db
  template:
    metadata:
      labels:
        app: alfa-romeo-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: alfa-romeo-env-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
