apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  # volumeName: webapp-pv
  # volumeName will exactly tell which pv the pvc to bind to, since im not using it, the kubernetes
  # handles this for me automatically 