# Generated by Django 5.0.3 on 2024-03-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AlterModelOptions(
            name='historycategory',
            options={'verbose_name_plural': 'History Categories'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='history',
            name='year',
        ),
    ]
