# Generated by Django 5.0.3 on 2024-03-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_created_history_created_by_history_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
