# Generated by Django 5.0.3 on 2024-03-11 14:35

import alfa_romeo_web.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alfaromeouser_groups_alfaromeouser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alfaromeouser',
            managers=[
                ('objects', alfa_romeo_web.accounts.managers.AlfaRomeoUserManager()),
            ],
        ),
    ]
