# Generated by Django 5.0.3 on 2024-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alfaromeouser',
            options={'verbose_name_plural': 'Alfa Romeo Website Users'},
        ),
    ]
