# Generated by Django 5.0.3 on 2024-04-06 07:52

import alfa_romeo_web.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone_number_profile_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[alfa_romeo_web.accounts.validators.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[alfa_romeo_web.accounts.validators.validate_profile_first_last_name, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[alfa_romeo_web.accounts.validators.validate_profile_first_last_name, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[alfa_romeo_web.accounts.validators.validate_profile_phone_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, validators=[alfa_romeo_web.accounts.validators.validate_profile_picture_url]),
        ),
    ]
