# Generated by Django 5.0.3 on 2024-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_field',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
