apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/django
    type: DirectoryOrCreate
  storageClassName: standard
