name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.x, ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alfa_romeo_web/requirements.txt

    - name: Install Playwright browsers
      run: |
        playwright install

    - name: Run Unit Tests
      run: |
        python alfa_romeo_web/manage.py test

    - name: Run UI Tests
      run: |
        python -m pytest alfa_romeo_web/tests/UI_tests
        
