name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: django_test_DB

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alfa_romeo_web/requirements.txt

    - name: Set up Database
      run: |
        sudo apt-get install -y postgresql-client
        psql -h localhost -U django -d postgres -c "CREATE DATABASE django_test_DB;"
      env:
        PGPASSWORD: django

    - name: Run Django Migrations
      run: |
        python alfa_romeo_web/manage.py migrate
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/django_test_DB

    - name: Install Playwright browsers
      run: |
        playwright install

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alfa_romeo_web/requirements.txt

    - name: Run Unit Tests
      run: |
        cd alfa_romeo_web
        python manage.py test
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/django_test_DB

  run_ui_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alfa_romeo_web/requirements.txt

    - name: Run UI Tests
      run: |
        python -m pytest alfa_romeo_web/tests/UI_tests
      env:
        DATABASE_URL: postgres://django:django@localhost:5432/django_test_DB
