name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: django_test_DB

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alfa_romeo_web/requirements.txt

    - name: Set up Database
      run: |
        sudo apt-get install -y postgresql-client
        psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d postgres -c "SELECT 'CREATE DATABASE django_test_DB' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'django_test_DB')\gexec"
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Run Django Migrations
      run: |
        python alfa_romeo_web/manage.py migrate
      env:
        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/django_test_DB

    - name: Install Playwright browsers
      run: |
        playwright install

    - name: Run Django Project
      run: |
        python alfa_romeo_web/manage.py runserver 127.0.0.1:8000
      env:
        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/django_test_DB

    - name: Run Unit Tests
      run: |
        python alfa_romeo_web/manage.py test
      env:
        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/django_test_DB

    - name: Run UI Tests
      run: |
        python -m pytest alfa_romeo_web/tests/UI_tests
      env:
        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/django_test_DB
